databases:
  - name: instaclone
    databaseName: instaclone
    user: admin

services:
  - type: web
    name: instaclone
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: instaclone
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
